import "./_style/globals.css";
import AuthContext from "./api/auth/AuthContext";
import {CssBaseline, ThemeProvider } from '@mui/material';
import theme from './_components/defaultTheme.js';
const metadata = {
  title: "인터뷰닷",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <ThemeProvider theme={theme}>
          <CssBaseline />
        <AuthContext>
        </AuthContext>
        {children}
        {/* <div className="flex-1 px-8 py-12 bg-gray-100">
        </div> 
          <main className="max-w-7xl mx-auto w-full"></main>
        */}
        </ThemeProvider>
      </body>
    </html>
  );
}
